In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/aoxiang/Desktop/数模国赛/C题/问题3/关键信息提取结果（完整信息）.csv")

In [3]:
data.describe()

,Y染色体浓度,孕妇BMI,18号染色体的Z值,年龄,身高,在参考基因组上比对的比例,检测孕周_天数
count,1082.000000,1082.000000,1082.000000,1082.000000,1082.000000,1082.000000,1082.000000
mean,0.299639,0.442676,0.411775,0.360906,0.550444,0.801807,0.324751
std,0.149493,0.113574,0.137987,0.166194,0.168780,0.060292,0.226463
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.184544,0.363202,0.320818,0.272727,0.451613,0.773033,0.126984
50%,0.290177,0.424443,0.403937,0.363636,0.548387,0.813853,0.277778
75%,0.396644,0.505241,0.492673,0.454545,0.677419,0.837965,0.500000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
data = pd.read_csv("/Users/aoxiang/Desktop/数模国赛/C题/问题3/关键信息提取结果(PCA).csv")
data.describe()

            Y染色体浓度        孕妇BMI      检测孕周_天数          主成分1
count  1082.000000  1082.000000  1082.000000  1.082000e+03
mean      0.077187    32.288791   117.918669  3.940163e-17
std       0.033518     2.972432    28.534298  1.033660e+00
min       0.010004    20.703125    77.000000 -2.643518e+00
25%       0.051381    30.208806    93.000000 -7.398598e-01
50%       0.075066    31.811598   112.000000 -8.776036e-02
75%       0.098937    33.926237   140.000000  6.260919e-01
max       0.234218    46.875000   203.000000  5.242075e+00