In [9]:
import pandas as pd

In [10]:
data = pd.read_csv('/Users/aoxiang/Desktop/数模国赛/C题/数据预处理/男胎检测数据.csv')

In [11]:
data[data["Y染色体浓度"]==data["Y染色体浓度"].min()]

,序号,孕妇代码,年龄,身高,体重,末次月经,IVF妊娠,检测日期,检测抽血次数,检测孕周,...,Y染色体浓度,X染色体浓度,13号染色体的GC含量,18号染色体的GC含量,21号染色体的GC含量,被过滤掉读段数的比例,染色体的非整倍体,怀孕次数,生产次数,胎儿是否健康
41,42,A010,23,150.0,75.0,2023-02-15 00:00:00,自然受孕,20230617,2,16w+4,...,0.010004,0.046679,0.380236,0.392723,0.402976,0.024494,NaN,1,0,是

In [12]:
data["Y染色体浓度"] < 0.04
data = data[data["Y染色体浓度"] < 0.04]
data

,序号,孕妇代码,年龄,身高,体重,末次月经,IVF妊娠,检测日期,检测抽血次数,检测孕周,...,Y染色体浓度,X染色体浓度,13号染色体的GC含量,18号染色体的GC含量,21号染色体的GC含量,被过滤掉读段数的比例,染色体的非整倍体,怀孕次数,生产次数,胎儿是否健康
0,1,A001,31,160.0,72.00,2023-02-01 00:00:00,自然受孕,20230429,1,11w+6,...,0.025936,0.038061,0.377069,0.389803,0.399399,0.027484,NaN,1,0,是
1,2,A001,31,160.0,73.00,2023-02-01 00:00:00,自然受孕,20230531,2,15w+6,...,0.034887,0.059572,0.371542,0.384771,0.391706,0.019617,NaN,1,0,是
27,28,A007,35,163.0,90.00,2023-04-18 00:00:00,自然受孕,20230718,1,12w+2,...,0.021902,0.029383,0.385940,0.398689,0.410119,0.022553,NaN,≥3,0,是
28,29,A007,35,163.0,90.00,2023-04-18 00:00:00,自然受孕,20230813,2,16w,...,0.038038,0.044189,0.381752,0.394462,0.406455,0.022558,NaN,≥3,0,是
29,30,A007,35,163.0,91.00,2023-04-18 00:00:00,自然受孕,20230915,3,20w+6,...,0.026984,0.029974,0.379346,0.391931,0.402020,0.023757,NaN,≥3,0,是
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,673,A165,26,160.0,85.00,2023-01-04 00:00:00,自然受孕,20230428,2,16w,...,0.036147,0.043661,0.375426,0.389394,0.398081,0.021758,NaN,≥3,1,是
677,678,A166,29,170.0,99.00,2023-01-20 00:00:00,自然受孕,20230704,4,22w+6,...,0.033394,0.022943,0.369514,0.382961,0.389614,0.020397,NaN,1,0,是
882,883,A218,29,161.0,89.61,2022-12-13,自然受孕,2023-03-08 00:00:00,1,12w+1,...,0.031356,0.066231,0.381249,0.392092,0.397248,0.025359,NaN,≥3,0,否
883,884,A218,29,161.0,89.85,2022-12-13,自然受孕,2023-03-15 00:00:00,2,13w+1,...,0.033963,-0.000078,0.379172,0.393835,0.400125,0.030339,NaN,≥3,0,否
884,885,A218,29,161.0,90.40,2022-12-13,自然受孕,2023-03-29 00:00:00,3,15w+1,...,0.039749,0.064700,0.377872,0.384003,0.398978,0.023593,NaN,≥3,0,否